# top-level key must match the dependency name in the umbrella helm chart
superset:
  image:
    repository: apache/superset
  # Superset node configuration
  supersetNode:
    replicaCount: 1
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 10
      targetCPUUtilizationPercentage: 80
      targetMemoryUtilizationPercentage: 80
  supersetCeleryBeat:
    # -- This is only required if you intend to use alerts and reports
    enabled: true
  supersetWorker:
    replicaCount: 3
    # Enable Alerts and Reports
    command:
      - /bin/sh
      - -c
      - |
        # Install chrome webdriver
        # See https://github.com/apache/superset/blob/4fa3b6c7185629b87c27fc2c0e5435d458f7b73d/docs/src/pages/docs/installation/email_reports.mdx
        apt-get update
        apt-get install -y wget
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        apt-get install -y --no-install-recommends ./google-chrome-stable_current_amd64.deb
        wget https://chromedriver.storage.googleapis.com/88.0.4324.96/chromedriver_linux64.zip
        apt-get install -y zip
        unzip chromedriver_linux64.zip
        chmod +x chromedriver
        mv chromedriver /usr/bin
        apt-get autoremove -yqq --purge
        apt-get clean
        rm -f google-chrome-stable_current_amd64.deb chromedriver_linux64.zip
  
        # Run
        . {{ .Values.configMountPath }}/superset_bootstrap.sh; celery --app=superset.tasks.celery_app:app worker    
  bootstrapScript: |
    #!/bin/bash
    pip install psycopg2==2.9.9 &&\
    if [ ! -f ~/bootstrap ]; then echo "Running Superset with uid {{ .Values.runAsUser }}" > ~/bootstrap; fi
  configOverrides:
    my_override: |
      # This will make sure the redirect_uri is properly computed, even with SSL offloading
      ENABLE_PROXY_FIX = True
      FEATURE_FLAGS = {
          "DYNAMIC_PLUGINS": True
      }
